### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by audiorecorder** [ffx0s/gif-editor#1]
Please tell me how to build it.
I'm just run "npm run-script build". but errors.

gif-editor-master>npm run-script build
> vue-cli-service build
 ERROR  Invalid options in vue.config.js: "vueLoader" is not allowed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gif-editor@0.1.7 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gif-editor@0.1.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by ffx0s** [comment]
> Please tell me how to build it.
> I'm just run "npm run-script build". but errors.
> 
> gif-editor-master>npm run-script build
> 
> > vue-cli-service build
> > ERROR  Invalid options in vue.config.js: "vueLoader" is not allowed
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! gif-editor@0.1.7 build: `vue-cli-service build`
> > npm ERR! Exit status 1
> > npm ERR!
> > npm ERR! Failed at the gif-editor@0.1.7 build script.
> > npm ERR! This is probably not a problem with npm. There is likely additional log
> > ging output above.

`npm run build`
